[package]
name = "generation-viewer"
version = "0.0.0"
edition = "2021"

[dependencies]
generation = { path = "../generation" }
geng = { version = "0.8.0-alpha.9", git = "https://github.com/kuviman/geng" }